@extends('frontend.layouts.app')

@section('content')
<section class="banner-section  about-parent position-relative about-sec py-sm-5 py-1">
    <div class="container">
        <div class="row align-items-center py-5 mt-4 mb-0 justify-content-start">
            <!-- <img class="img-fluid banner-img" src="./assets/images/banner-ing.png" alt="about-img"> -->
            <div class="col-md-8">
                <h1 class="text-white text-start">Terms and Conditions</h1>
                <div class="parent-banner-btn text-start mt-4 mb-2">
                        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{url('/')}}" class="text-decoration-none text-white">Home</a>
                                </li>
                                <li class="breadcrumb-item active" aria-current="page"><a href="" class="text-decoration-none text-white">Terms and Conditions</a></li>
                            </ol>
                        </nav>
                    </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="privacy-inner">
            <p><b>MedisourceRx Terms and Conditions (Privacy policy incorporated into it) 
                These Terms & Conditions (“Terms”) govern your access to and use of this website and related online services made available to you via this website (“Services”) by MedisourceRx, LLC, (“MedisourceRx”, “we”, “us” or “our”).
                </b>
            </p>
            <p>ARBITRATION NOTICE; CLASS WAIVER; WAIVER OF TRIAL BY JURY. These Terms contain a binding arbitration provision. You agree that all disputes between you and Company will be resolved by mandatory binding arbitration and you waive any right to participate in a class action lawsuit or class-wide arbitration.
            </p>
            <div>
                <ol>
                    <li><b>Acceptance of Terms and Amendments</b> 
                        <p>Each time you use or cause access to this website, you agree to be bound by these Terms. We may modify these Terms at any time. All changes will be effective immediately upon posting to the Services. Material changes will be conspicuously posted on the Services or otherwise communicated to you. By using the Services after changes are posted, you agree to those changes.</p>
                        <p>In addition, if you are using a particular service on or accessed via this website, you will be subject to any rules or guidelines applicable to those services, and they will be incorporated by reference within these Terms. Please read the website’s Privacy Policy, which is incorporated within these Terms of use by reference.</p>
                    </li>
                    <li><b>The Service</b></li>
                        <p>This website and the services provided to you on and via this website are provided on an “AS IS” basis. You agree that we have the right to modify or discontinue provision of this website and its services, and to remove the data you provide, either temporarily or permanently, at any time, without notice and without any liability towards you. We will not be held responsible or liable for timeliness, removal of information, failure to store information, inaccuracy of information, or improper delivery of information.</p>
                    <li><b>Your responsibilities and registration obligations</b></li>
                        <p>In order to use certain Services offered through the website, you may be required to register for a user account. You agree to provide truthful and accurate information regarding your account. By registering an account, you represent that you are at least 18 years of age. By registering for a user account, you explicitly agree to these Terms.</p>
                    <li><b>Privacy policy</b></li>
                        <p>Registration data and other personally identifiable information that the website may collect is subject to the terms of our Privacy Policy.</p>
                    <li><b>Registration and password</b></li>
                        <p>You are responsible for maintaining the confidentiality of the username and password for your account and you will be responsible for all usage of your username and/or password, whether authorized or not authorized by you. Please log out of your account at the end of each session. In connection with your access to and use of the Services and that of any person you permit to access and use the Services using your account, you are responsible for complying with all applicable laws, regulations, and policies of all relevant jurisdictions. You agree to immediately notify us of any unauthorized use of your user account, username, or password at the following email address: <b><a href="mail:info@medisourcerx.com. " class="text-call-mail-color text-decoration-none">info@medisourcerx.com.</a></b></p>
                    <li><b>Orders and Return Policy</b></li>
                        <p>You may place orders for fulfillment of your prescriptions through the Services available under your account. All offers on the website are void where prohibited by law. Advertised prices and available quantities may change at any time without notice to you. Some products and services may not be available in certain areas. The data on the website may contain technical inaccuracies, typographical errors, or omissions. All purchases placed through the Site are subject to these Terms. In our sole discretion, we may refuse or cancel any order for any reason. Quantities are limited. Resale of products or services purchased through the Services is expressly prohibited. There may be certain orders that we cannot accept and must cancel. In our sole discretion, we may refuse or cancel any order for any reason.  We regret that we cannot accept returns on any custom compounds as state and federal regulations prohibit the return and resale of such items. All products are non-returnable and non-refundable. However, if you feel we have made an error in filling your order or your order arrives damaged, please contact Customer Support at <a href="tel:(714) 455-1300" class="text-call-mail-color text-decoration-none">(714) 455-1300</a> within 24 hours of receiving your order for assistance.</p>
                    <li><b>Payment Data</b></li>
                        <p>Prescriptions filled through the Services must be paid by credit or with debit card. Acceptance of any order is subject to our verification and credit card approval process. The credit or debit card you provide will be linked to your account as your default form of payment for future prescriptions. You may change the credit card linked to your account at any time by calling Customer Support at <a href="tel:(714) 455-1300" class="text-call-mail-color text-decoration-none">(714) 455-1300</a>. You represent and warrant that we have the authorization to use any credit or debit card that you provide to us.  If the credit or debit card data that you submit is incorrect or invalid, your payment will not be processed. We have no responsibility or liability if your financial institution declines your credit or debit card. Payments are processed by our PCI-compliant third-party payment processor. Additional information about our collection and use of payment-related data is described in our Privacy Policy</p>
                    <li><b>Shipping and Handling</b></li>
                        <p>Unless otherwise noted, shipping and handling fees will be charged separately. Sales, use and similar taxes will be charged to you to the extent required by law. We do not ship outside the continental United States.</p>
                    <li><b>License; Term</b></li>
                        <p>Provided you comply with these Terms, MedisourceRx grants you a limited, nonexclusive, revocable, non-assignable, non-transferable, non-sublicensable license to access and use the Services solely for your own personal purposes as permitted by these Terms. These Terms begin upon your creation of an account (or, if earlier, your first access to or use of the Services) and will continue in effect until terminated in accordance with these Terms.</p>
                    <li><b>Intellectual Property Rights</b></li>
                        <p>The term “Services” includes all text, audio, video, graphics, charts, photographs, interfaces, icons, software, computer code, databases, trademarks, logos, slogans, names of products and services, documentation, other components and content, and the design, selection, and arrangement of content. The Services are exclusively the property of Company or its licensors. The Services are protected by copyright, trademark, and other intellectual property laws. Any unauthorized use of the Services or related intellectual property belonging to Company or any third party is strictly prohibited. The Services may contain references to third-party marks and copies of third-party copyrighted materials, which are the property of their respective owners.</p>
                    <li><b>Your conduct</b></li>
                        <p>By using this website or any Service provided, you explicitly agree that:</p>
                        <p>(a) you will not provide any content or conduct yourself in any way that may be construed as: unlawful; illegal; threatening; harmful; abusive; harassing; stalking; tortious; defamatory; libelous; vulgar; obscene; offensive; objectionable; pornographic; designed to interfere with or disrupt the operation of this web site or any service provided; infected with a virus or other destructive or deleterious programming routine; giving rise to civil or criminal liability; or in violation of an applicable local, national or international law;</p>
                        <p>(b) you will not impersonate or misrepresent your association with any person or entity; you will not forge or otherwise seek to conceal or misrepresent the origin of any content provided by you;</p>
                        <p>(c) you will not collect or harvest any information about other users or engage in data mining or use any indexing agents, spiders, scrapers, bots, web crawlers or other automated devices;</p>
                        <p>(d) you will not provide, and you will not use this web site to provide, any content or service in any commercial manner, or in any manner that would involve junk mail, spam, chain letters, pyramid schemes, or any other form of unauthorized advertising or commerce; you will not use this web site to promote or operate any service or content without our prior written consent;</p>
                        <p>(e) if you submit the personal information of any person other than yourself in setting up your account or otherwise in using the Services, you have that person’s permission to provide us with that information;</p>
                        <p>(f) you will not modify or delete any copyright, trademark or other proprietary notices;</p>
                        <p>(g) you will not copy, reproduce, display, duplicate, sell, publish, post, license, rent, distribute, modify, translate, adapt, reverse-engineer, decompile, disassemble, or create any derivative works of the Services or any part of the Services (including the website) without our prior written consent; and</p>
                        <p>(h) you will not circumvent any of our security measures or engage in activities to render the Services or the website inoperable or its use more difficult.</p>
                    <li><b>Submission of content on this web site</b></li>
                        <p>By providing any content to this web site:</p>
                        <p>(a) you agree to grant us a worldwide, royalty-free, perpetual, non-exclusive right and license (including any moral rights or other necessary rights.) to use, display, reproduce, modify, adapt, publish, distribute, perform, promote, archive, translate, and to create derivative works and compilations, in whole or in part, including the right to sublicense the same. Such license will apply with respect to any form, media, and technology already known at the time of provision or developed subsequently.</p>
                        <p>(b) you warrant and represent that you have all legal, moral, and other rights that may be necessary to grant the license specified in this section; and</p>
                        <p>(c) you acknowledge and agree that we have the right (but not obligation), at our entire discretion, to refuse to publish, or to remove, or to block access to any content you provide, at any time and for any reason, with or without notice.</p>
                    <li><b>Third-party content and services</b></li>
                        <p>Goods and services of third parties may be advertised and/or may be made available on or through this web site. Representations made regarding products and services provided by third parties will be governed by the policies and representations made by these third parties. We are not in any manner liable for or responsible for any of your dealings or interaction with third parties.</p>
                        <p>In addition, portions of the content on this web site may have been contributed by third parties.  The inclusion of such information does not indicate any approval or endorsement by MedisourceRx of such content, and MedisourceRx expressly disclaims any liability with respect to the foregoing.</p>
                    <li><b>Third-Party Websites</b></li>
                        <p>The Services may link to, or be linked to, websites not maintained or controlled by MedisourceRx. Those links are provided as a convenience and MedisourceRx is not responsible for examining or evaluating the content or accuracy of, and does not warrant or endorse, any third-party webRx, or any products or services made available through those websites. Please take care when leaving this website to visit a third-party website. You should read the terms of use and privacy policy for each website that you visit.</p>
                        <p>Additionally, other websites may link to this website with or without our authorization.  You acknowledge and agree that MedisourceRx and its affiliates, customers, suppliers and agents do not endorse such websites, and are not and shall not be responsible or liable for any links from those websites to this website, any content, advertising, products or other materials available on or through such other websites, or any loss or damages incurred in connection therewith.  We shall have the right, at any time and in our sole discretion, to block links to this website through technological or other means without prior notice.</p>
                    <li><b>Content Provided by MedisourceRx</b></li>
                        <p>The content provided by MedisourceRx on this web site and all site-related services is intended to educate and inform you about MedisourceRx, our product candidates and our technology.  Although we strive to provide content that is both useful and accurate, laws, regulations, data and other information change frequently.  In addition, the facts and circumstances of every situation differ.  Accordingly, although MedisourceRx endeavors to use reasonable care in assembling the content that we provide on this web site, some of it may not be accurate or complete.  In addition, although we try to keep the web site up-to-date, we assume no duty to update any of the content on the web site, all of which speaks only as of the date of its posting.  Please contact MedisourceRx to determine whether you have the most recent version of the content that we generally make available on this web site, although even the most recent version available from MedisourceRx may not be up-to-date, accurate or complete.</p>
                        <p>We hope that the content that we have provided on this website will be helpful as background reference, but it should in no way be considered legal, accounting or other professional advice on any subject matter.  MedisourceRx is not engaged in rendering legal, accounting or other professional services, and the availability or use of this web site is not intended to create, and does not create, any attorney-client, accounting-client or other professional services relationship.  Use of this web site is not an adequate substitute for obtaining legal, accounting or other professional advice.  You should not take action based on any of the content on the web site without first seeking the services of a competent professional, and any such action that you elect to take is at your own risk.</p>
                    <li><b>Account Suspension, Deactivation, and Termination</b></li>
                        <p>To the maximum extent permitted by applicable law, we may, for any reason and in its sole discretion, suspend, deactivate, or terminate your account and your use of the Services, without notice or liability. If we suspend, deactivate, or terminate your account, you may not create another MedisourceRx account without our prior written permission. You may terminate your account at any time by contacting us using the contact information below.</p>
                    <li><b>Forward Looking Statements and Investor Information</b></li>
                        <p>The content on this page may contain information that includes or is based upon forward-looking statements within the meaning of the Private Securities Litigation Reform Act of 1995.  Forward-looking statements give our expectations or forecasts of future events.  You can identify these statements by the fact that they do not relate strictly to historical or current facts.  They may use words such as “anticipate”, “estimate”, “expect”, “project”, “intend”, “plan”, “believe”, or other words and terms of similar meaning in connection with a discussion of future operating or financial performance.  In particular, these include statements relating to future actions, prospective products, clinical trial procedures and results, future performance, results of current and anticipated products, expenses, the outcome of contingencies such as legal proceedings, and financial results.</p>
                        <p>Any or all the forward-looking statements we make could turn out to be wrong. They can be affected by inaccurate assumptions or by known or unknown risks and uncertainties. Many such factors will be important in determining our actual future results. Consequently, no forward-looking statement can be guaranteed. Our actual results may vary materially, and there are no guarantees about the performance of our stock.</p>
                        <p>We undertake no obligation to correct or update any forward-looking statements, whether as a result of new information, future events or otherwise.  You are advised to consult any disclosures we make on related subjects in our recent reports filed with the Securities and Exchange Commission. In particular, you should read disclosures in those documents identified under the heading “Risk Factors.”</p>
                        <p>The information on this website may not be current and should not be used or relied on for any decision to invest in, purchase, retain, sell or otherwise transfer the stock of MedisourceRx or for any related purpose.</p>
                        <p>The information provided on this web site does not constitute an offer to purchase shares of MedisourceRx and is not aimed at investors or potential investors in MedisourceRx stock.  Any decision to invest in MedisourceRx should be based on separate material approved by MedisourceRx.  Furthermore, MedisourceRx reserves the right to change or supplement the information provided on this web site.</p>
                        <p>All stock price information provided on this web site is for informational purposes only, and is not intended, and should not be relied on, for investment purposes.  Historical and current stock price information is not indicative of future performance.  All stock price information has been provided by a third-party source and not by MedisourceRx, and MedisourceRx makes no representations or warranties as to the sequence, accuracy, or completeness of any stock price information or other related data displayed on this web site.  MedisourceRx shall not be responsible or liable in any way to a web site visitor for any delays, inaccuracies, errors in, or omission of any such stock price information or related data or the transmission thereof, or for any actions taken in reliance thereon or for any damages arising therefrom or occasioned thereby or by reason of nonperformance or interruption, or termination, of the stock price information for any cause whatsoever.</p>
                    <li><b>Indemnification</b></li>
                        <p>You agree to indemnify and hold harmless MedisourceRx and our representatives, subsidiaries, affiliates, related parties, officers, directors, employees, agents, independent contractors, advertisers, partners, and co-branders, from any loss, damage, expense, claim or demand, including reasonable legal fees, that may be filed by any third party, arising out of your conduct or connection with this website or Service, your provision of content, your violation of these Terms, or any other violation by you of the rights of another person or party.</p>
                    <li><b>DISCLAIMER OF WARRANTIES</b></li>
                        <p>YOU UNDERSTAND AND AGREE THAT YOUR USE OF THIS WEBSITE OR OF ANY SERVICES OR CONTENT PROVIDED IS AT YOUR OWN RISK. SERVICES AND CONTENT ARE PROVIDED TO YOU “AS IS”, AND MEDISOURCERX EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, EITHER IMPLIED OR EXPRESS, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. MEDISOURCERX MAKES NO WARRANTY, EITHER IMPLIED OR EXPRESS, THAT ANY PART OF THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, VIRUS-FREE, TIMELY, SECURE, ACCURATE, RELIABLE, OR OF ANY QUALITY, NOR IS IT WARRANTED EITHER IMPLICITLY OR EXPRESSLY THAT ANY CONTENT IS SAFE IN ANY MANNER FOR DOWNLOAD. YOU UNDERSTAND AND AGREE THAT NEITHER MEDISOURCERX NOR ANY PARTICIPANT IN THE SERVICE PROVIDES PROFESSIONAL ADVICE OF ANY KIND AND THAT ANY ADVICE OR ANY OTHER INFORMATION OBTAINED VIA THIS WEB SITE MAY BE USED SOLELY AT YOUR OWN RISK, AND THAT MEDISOURCERX WILL NOT BE HELD LIABLE IN ANY WAY.</p>
                        <p>Some jurisdictions may not allow disclaimers of implied warranties, and certain statements in the above disclaimer may not apply to you as regards implied warranties; the other terms and conditions remain enforceable notwithstanding.</p>
                    <li><b>LIMITATION OF LIABILITY</b></li>
                        <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT NEITHER MEDISOURCERX NOR ANY OF ITS AFFILIATES, LICENSORS, SPONSORS, DIRECTORS, OFFICERS, EMPLOYEES, CONSULTANTS, AGENTS OR REPRESENTATIVES WILL BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL PUNITIVE OR EXEMPLARY DAMAGES. UNDER ANY THEORY OF LIABILITY, ARISING OUT OF OR RELATING IN ANY WAY TO THE WEBSITE, THE SERVICES OR THE CONTENT. THIS INCLUDES, BUT IS NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM (I) THE USE OF SERVICES OR THE INABILITY TO USE THE SERVICES, (II) THE COST OF OBTAINING SUBSTITUTE GOODS AND/OR SERVICES RESULTING FROM ANY TRANSACTION ENTERED INTO ON OR THROUGH THE SERVICES, (III) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR DATA TRANSMISSIONS, (IV) STATEMENTS BY ANY THIRD PARTY OR CONDUCT OF ANY THIRD PARTY USING SERVICES, OR (V) ANY OTHER MATTER RELATING TO THE SERVICES. THE SOLE AND EXCLUSIVE MAXIMUM LIABILITY OF MEDISOURCERX FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION SHALL BE THE TOTAL AMOUNT PAID BY YOU, IF ANY, TO ACCESS THIS WEBSITE AND SERVICES (EXCLUSIVE OF ANY INTERNET ACCESS FEES OR COSTS OF COMPUTER OR OTHER EQUIPMENT THAT YOU MAY USE IN ACCESSING THE WEBSITE).</p>
                        <p>In some jurisdictions, it is not permitted to limit liability and, therefore, such limitations may not apply to you.</p>
                    <li><b>Notification of copyright infringement</b></li>
                        <p>If you believe that your property has been used in any way that could be considered a copyright infringement or a violation of your intellectual property rights, our copyright agent may be contacted via: e-mail to the site administrator</p>
                    <li><b>Applicable law</b></li>
                        <p>You agree that these Terms of use and any dispute arising out of your use of this web site or products, or services provided will be governed by and construed in accordance with the laws of California notwithstanding any differences between the said applicable legislation and legislation in force at your location. By registering for a user account on this web site, or by using this web site and the services it provides, you accept that jurisdiction is granted to the courts in the state of California, and that any disputes will be heard by the said courts.</p>
                        <p>We reserve the right to terminate this service, in whole or in part, at any time without notice.</p>
                    <li><b>Arbitration Agreement; Class Waiver; Waiver of Trial by Jury</b></li>
                        <p>Please read the following paragraphs carefully because they require you to arbitrate disputes with Company and limit the manner in which you can seek relief from us.</p>
                        <ul>
                            <li><b>Applicability of Arbitration Agreement.</b></li>
                                <p>1. Any dispute, claim or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation or validity hereof, including the determination of the scope or applicability of these Terms to arbitrate (hereinafter, collectively, the “Dispute”), which cannot be resolved informally, shall be resolved by binding arbitration on an individual basis under the terms set forth below (the “Arbitration Agreement”). Notwithstanding the foregoing, in the event of any actual, alleged or threatened violation of confidentiality or violation of the Company’s intellectual property or other proprietary rights, Company may immediately resort to court proceedings in a court of competent jurisdiction as set forth above in order to seek immediate injunctive relief without posting of a bond, proof of damages or other similar requirement. The institution of any action for injunctive relief shall not constitute a waiver of the right or obligation of any party to submit any claim seeking relief other than injunctive relief to arbitration.</p>
                                <p>2. This Arbitration Agreement applies to you and Company, and to any of our subsidiaries, affiliates, agents, employees, predecessors in interest, successors in interest, and assigns, as well as all authorized or unauthorized users or beneficiaries of the Services provided under the Terms.</p>
                            <li><b>Arbitrator</b></li>
                                <p>The arbitration proceeding will be administered by the American Arbitration Association (“AAA”) before an arbitrator selected pursuant to the AAA rules. The decision of the arbitrator will be final and binding. Any final award or judgment may be filed and enforced in any court of competent jurisdiction. The parties shall share equally in the costs assessed for the arbitration, and each party shall bear its own attorneys’ fees and costs. Any arbitration proceeding may not be consolidated or joined with any other proceeding and will not proceed as a class action. The parties understand that they would have had a right or opportunity to litigate disputes through a court, to have a judge or jury decide their case, and to participate in a class action or other proceeding involving multiple claimants, but they instead choose and agree to have all disputes as set forth herein decided through individual arbitration.</p>
                            <li><b>Place</b></li>
                                <p>The place of arbitration shall be in Orange County, California, unless otherwise agreed to in writing by all parties to the arbitration. The parties acknowledge that this Arbitration Agreement evidences a transaction involving interstate commerce, and the Federal Arbitration Act, 9 U.S.C. Sections 1–16, shall govern the interpretation, enforcement and proceedings pursuant to this Arbitration Agreement. The parties expressly agree that any and all actions taken under the Arbitration Agreement and related provisions, including but not limited to all filings, orders, judgments, and awards made in any arbitration proceeding, are confidential and may not be disclosed to any third party.</p>
                            <li><b>Survival</b></li>
                                <p>This Arbitration Agreement provision will survive the termination of these Terms.</p>
                        </ul>
                    <li><b>Miscellaneous information</b></li>
                        <p>(i) In the event that any provision of these Terms is deemed to be unlawful by any court or arbitration, the offending provision will be interpreted to reflect the original intentions of the parties to the extent possible in accordance with applicable law, and the remainder of these Terms will remain valid and applicable.</p>
                        <p>(ii) The failure of either party to assert any right under these Terms will not be considered to be a waiver of that party’s right, and the said right will remain in full force and effect</p>
                        <p>(iii) You agree that any claim or cause in respect of this website or its services must be filed within one (1) year after such claim or cause arose, or the said claim or cause will be forever barred, without regard to any contrary legislation</p>
                    <li><b>Contact Us</b></li>
                        <p>Please direct any questions and concerns regarding these Terms to us at:</p>
                            <ul>
                                <li>By Mail: Attn: Paul Kagan, MedisourceRx LLC dba Seaview Enterprise,
                                    10525 Humbolt Street, Los Alamitos, CA  90720
                                </li>
                                <li>By Phone: <a href="tel:+17144551300" class="text-call-mail-color text-decoration-none">(714) 455-1300</a> | By Fax: <a href="tel:+17144551300" class="text-call-mail-color text-decoration-none">(714) 455-1300</a></li>
                            </ul>
                            <br>
                    <li><b>California Users</b></li>
                        <p>Under California Civil Code Section 1789.3, California users of the Services receive the following specific consumer rights notice: The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 1020 N Street, #501, Sacramento, California 95814, or by telephone at (916) 445-1254.</p>
                </ol>
            </div>
        </div>
    </div>
</section>
@endsection
